-- begin CEDG_WORKGROUP
alter table CEDG_WORKGROUP add constraint FK_CEDG_WORKGROUP_ON_TOWN_HALL foreign key (TOWN_HALL_ID) references CEDG_TOWN_HALL(ID)^
create index IDX_CEDG_WORKGROUP_ON_TOWN_HALL on CEDG_WORKGROUP (TOWN_HALL_ID)^
-- end CEDG_WORKGROUP

-- begin CEDG_EMPLOYEE
alter table CEDG_EMPLOYEE add constraint FK_CEDG_EMPLOYEE_ON_SYSTEM_USER foreign key (SYSTEM_USER_ID) references SEC_USER(ID)^
create index IDX_CEDG_EMPLOYEE_ON_SYSTEM_USER on CEDG_EMPLOYEE (SYSTEM_USER_ID)^
-- end CEDG_EMPLOYEE
-- begin CEDG_TOWN_HALL_EMPLOYEE_LINK
alter table CEDG_TOWN_HALL_EMPLOYEE_LINK add constraint FK_TOWHALEMP_ON_TOWN_HALL foreign key (TOWN_HALL_ID) references CEDG_TOWN_HALL(ID)^
alter table CEDG_TOWN_HALL_EMPLOYEE_LINK add constraint FK_TOWHALEMP_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references CEDG_EMPLOYEE(ID)^
-- end CEDG_TOWN_HALL_EMPLOYEE_LINK
-- begin CEDG_EMPLOYEE_WORKGROUP_LINK
alter table CEDG_EMPLOYEE_WORKGROUP_LINK add constraint FK_EMPWOR_ON_WORKGROUP foreign key (WORKGROUP_ID) references CEDG_WORKGROUP(ID)^
alter table CEDG_EMPLOYEE_WORKGROUP_LINK add constraint FK_EMPWOR_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references CEDG_EMPLOYEE(ID)^
-- end CEDG_EMPLOYEE_WORKGROUP_LINK
