alter table CEDG_EMPLOYEE add constraint FK_CEDG_EMPLOYEE_ON_SYSTEM_USER foreign key (SYSTEM_USER_ID) references SEC_USER(ID);
create index IDX_CEDG_EMPLOYEE_ON_SYSTEM_USER on CEDG_EMPLOYEE (SYSTEM_USER_ID);
